services:
    # GRIDS
    skrepr_datagrid.datagrid:
        class: Skrepr\DatagridBundle\Service\Datagrid
        arguments:
            - 'collectie met grids'
            - '@service_container'
            - '%skrepr_datagrid.view.path%'
            - '@doctrine.orm.entity_manager'

    skrepr_datagrid.datagrid_base: # TODO naam??
        class: Skrepr\Datagrid\Datagrid
        calls:
            - [ setViewPath, [ '%skrepr_datagrid.view.path%' ] ]
